# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import os
import requests
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QTextEdit, QPushButton, QVBoxLayout, QHBoxLayout, QMessageBox
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QFont

# Cấu hình đường dẫn plugin Qt từ ảnh gốc của bài học
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class ECCCipherUI(QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()
        
    def initUI(self):
        font_label = QFont('Arial', 10, QFont.Bold)
        
        # 1. Header Title and Generate Keys Button
        title_label = QLabel('ECC CIPHER')
        title_font = QFont('Arial', 16, QFont.Bold)
        title_label.setFont(title_font)
        
        self.btn_generate_keys = QPushButton('Generate Keys')
        self.btn_generate_keys.setFixedWidth(120)
        self.btn_generate_keys.setFixedHeight(30)
        self.btn_generate_keys.clicked.connect(self.handle_generate_keys)
        
        header_layout = QHBoxLayout()
        header_layout.addWidget(title_label, alignment=Qt.AlignLeft)
        header_layout.addStretch()
        header_layout.addWidget(self.btn_generate_keys, alignment=Qt.AlignRight)
        
        # 2. Information Block (Chữ nằm ngang hàng với ô nhập)
        info_label = QLabel('Information:')
        info_label.setFont(font_label)
        info_label.setFixedWidth(90)  # Cố định độ rộng nhãn chữ để ô nhập thẳng hàng nhau
        self.txt_information = QTextEdit()
        self.txt_information.setFixedHeight(100)
        
        info_row_layout = QHBoxLayout()
        info_row_layout.addWidget(info_label, alignment=Qt.AlignTop)  # Căn chữ nằm ở mép trên
        info_row_layout.addWidget(self.txt_information)
        
        # 3. Signature Block (Chữ nằm ngang hàng với ô nhập)
        sig_label = QLabel('Signature:')
        sig_label.setFont(font_label)
        sig_label.setFixedWidth(90)  # Thiết lập bằng độ rộng nhãn trên để căn lề đều nhau
        self.txt_signature = QTextEdit()
        self.txt_signature.setFixedHeight(100)
        
        sig_row_layout = QHBoxLayout()
        sig_row_layout.addWidget(sig_label, alignment=Qt.AlignTop)  # Căn chữ nằm ở mép trên
        sig_row_layout.addWidget(self.txt_signature)
        
        # 4. Sign & Verify Action Buttons
        self.btn_sign = QPushButton('Sign')
        self.btn_sign.setFixedWidth(100)
        self.btn_sign.setFixedHeight(30)
        self.btn_sign.clicked.connect(self.handle_sign)
        
        self.btn_verify = QPushButton('Verify')
        self.btn_verify.setFixedWidth(100)
        self.btn_verify.setFixedHeight(30)
        self.btn_verify.clicked.connect(self.handle_verify)
        
        button_layout = QHBoxLayout()
        button_layout.addStretch()
        button_layout.addWidget(self.btn_sign)
        button_layout.addSpacing(40) 
        button_layout.addWidget(self.btn_verify)
        button_layout.addStretch()
        
        # 5. Main Layout Assembly
        main_layout = QVBoxLayout()
        main_layout.setContentsMargins(30, 20, 30, 20)
        main_layout.setSpacing(15)
        
        main_layout.addLayout(header_layout)
        main_layout.addLayout(info_row_layout)  # Thêm hàng ngang Information
        main_layout.addLayout(sig_row_layout)   # Thêm hàng ngang Signature
        main_layout.addLayout(button_layout)
        
        self.setLayout(main_layout)
        self.setWindowTitle('ECC Cipher - [Preview] - Qt Designer')
        self.resize(600, 380)  # Tăng nhẹ chiều rộng để tạo không gian cho nhãn chữ nằm ngang

    # --- API LOGIC HANDLERS ---
    def handle_generate_keys(self):
        try:
            response = requests.get('http://127.0.0.1:5000/api/ecc/generate_keys')
            if response.status_code == 200:
                QMessageBox.information(self, "Success", response.json().get('message'))
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Could not connect to the API Server: {e}")

    def handle_sign(self):
        message = self.txt_information.toPlainText()
        if not message:
            QMessageBox.warning(self, "Warning", "Please enter some text into the Information field!")
            return
        try:
            response = requests.post('http://127.0.0.1:5000/api/ecc/sign', json={'message': message})
            if response.status_code == 200:
                signature = response.json().get('signature')
                self.txt_signature.setPlainText(signature)
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Could not connect to the API Server: {e}")

    def handle_verify(self):
        message = self.txt_information.toPlainText()
        signature = self.txt_signature.toPlainText()
        if not message or not signature:
            QMessageBox.warning(self, "Warning", "Please provide both Information and Signature!")
            return
        try:
            response = requests.post('http://127.0.0.1:5000/api/ecc/verify', json={'message': message, 'signature': signature})
            if response.status_code == 200:
                is_verified = response.json().get('is_verified')
                if is_verified:
                    QMessageBox.information(self, "Result", "Signature is VALID! (True)")
                else:
                    QMessageBox.warning(self, "Result", "Signature is INVALID! (False)")
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Could not connect to the API Server: {e}")

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = ECCCipherUI()
    ex.show()
    sys.exit(app.exec_())